Added build script to create, package & publish plugins
craftercms/plugin-maker pull request #3
Opened 2018-01-16 22:04 UTC by jdrossl

https://github.com/craftercms/craftercms/issues/1741

2018-01-16 22:19 UTC, avasquez614 approved these changes

2018-01-17 01:56 UTC, sumerjabri requested changes

2018-01-17 01:56 UTC, sumerjabri commented on resources/template/plugin.xml
> +      <min>4.0.0</min>
3.1.0 start
3.1.0 finish

2018-01-17 01:56 UTC, sumerjabri commented on resources/template/plugin.xml
> +    <!-- Can be http:// or relative URL -->
http(s)?

2018-01-17 01:56 UTC, sumerjabri commented on build.gradle
> +// import org.eclipse.egit.github.core.Issue
Do we need this commented out code block?

2018-01-17 01:56 UTC, sumerjabri commented on build.gradle
> +      // ant.input(message: 'Pelase type your username', addproperty: 'username')
`Please` (typo)

Also, shouldn't this indicate that you're asking for github creds?

2018-01-17 19:27 UTC, merged